name: Publish on GitHub

on: [ push, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.1                       
  JAVA_VERSION: 17                   

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest              
    permissions:
      contents: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
          
      - 
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          
      - 
        name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
        
      - 
        name: Build
        run: ./gradlew clean build

      - 
        name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}